### ISSUE TITLE
Debug Mode

### ISSUE THREAD

**Issue by delta2323** [pfnet/chainer#457]
One of the most appealing point of Chainer is easiness of debugging. But verbose assertions can cause much overhead. 

This PR proposes debug mode during forward and backward operations.
Possible feature includes
- [x] Detection of `inf` and `nan`
- [x] More assertion of the condition (e.g. #302)
- [x] Check of inconsistency in `grad` and `data` (cf. #278)
- [ ] Visualize errors by computational graph (cf. #252)
* ...

**Comment by delta2323** [comment]
Another alternative is to implement Fast mode (or Unsafe mode) in which Chainer passes to some extent procedures that can be bottlenecks.

**Comment by unnonouno** [comment]
I found that we can easily check inconsistency between `grad` and `data`.

**Comment by unnonouno** [comment]
This issue is fixed via #899, #934 and #935. We show stacktrace of forward computation when an error occurs on backward instead of visualizing computational graph.
